FROM rust:1-bookworm

COPY ./Cargo.* ./
COPY ./crates ./crates

# Add .git to crates/node in order to build version metadata into binary.
COPY ./.git ./crates/node/.git

RUN apt-get update && apt-get upgrade -y && apt-get install -y \
  libssl-dev \
  protobuf-compiler

RUN cargo build --release

FROM debian:bookworm

# Copy Gevulot node bin from earlier build step.
COPY --from=0 target/release/gevulot-cli /gevulot-cli

# Install QEMU.
RUN apt-get update && apt-get upgrade -y && apt-get install -y --no-install-recommends \
  ca-certificates \
  curl \
  qemu-system

COPY ./crates/node/migrations /migrations

RUN mkdir -p /var/lib/gevulot

ENTRYPOINT ["/gevulot-cli"]
