FROM debian:bookworm

# Install QEMU.
RUN apt-get update && apt-get upgrade -y && apt-get install -y --no-install-recommends \
  ca-certificates \
  curl \
  qemu-system

COPY ./data/crates/gevulot /gevulot
COPY ./crates/node/migrations /migrations

RUN mkdir -p /var/lib/gevulot

# RUN /gevulot generate key --key-file /var/lib/gevulot/node.key

CMD ["run"]
ENTRYPOINT ["/gevulot"]
