name: Build Gevulot

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: ghcr.io
  BUILD_PREFIX: "1.0"
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.2.0

      - name: Inspect builder
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Build and push gevulot-crates
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: Containerfile-gevulot-crates
          build-args: |
            "BUILD_NUMBER=${{ env.BUILD_PREFIX }}.${{ github.run_number }}"
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/nct-labs/gevulot-crates:latest
            ${{ env.DOCKER_REGISTRY }}/nct-labs/gevulot-crates:v${{ env.BUILD_PREFIX }}.${{ github.run_number }}

      - name: Copy binaries
        run: |
          docker run --rm -it -v ./data/crates:/tmp/crates:z gevulot-crates:latest cp -R /target/release/{gevulot,gevulot-cli,gevulot-e2e-tests,prover,verifier} /tmp/crates/

      - name: Build and push gevulot-cli
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: Containerfile-gevulot-cli
          build-args: |
            "BUILD_NUMBER=${{ env.BUILD_PREFIX }}.${{ github.run_number }}"
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/nct-labs/gevulot-cli:latest
            ${{ env.DOCKER_REGISTRY }}/nct-labs/gevulot-cli:v${{ env.BUILD_PREFIX }}.${{ github.run_number }}
             
      - name: Build and push gevulot
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: Containerfile-gevulot
          build-args: |
            "BUILD_NUMBER=${{ env.BUILD_PREFIX }}.${{ github.run_number }}"
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/nct-labs/gevulot:latest
            ${{ env.DOCKER_REGISTRY }}/nct-labs/gevulot:v${{ env.BUILD_PREFIX }}.${{ github.run_number }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.BUILD_PREFIX }}.${{ github.run_number }}
          release_name: v${{ env.BUILD_PREFIX }}.${{ github.run_number }}
          draft: false
          prerelease: true
          body: |
            ${{ github.event.head_commit.message }}
            Packages available at https://github.com/nct-labs/gevulot/pkgs/container/${{ env.PROJECT_NAME }}
